# Generated by Django 3.0.7 on 2020-06-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentingBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('service', models.TextField(max_length=1000)),
                ('idMotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.motel')),
            ],
        ),
    ]
