# Generated by Django 3.0.7 on 2020-06-05 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='motel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('update_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('phone', models.IntegerField(default=0)),
                ('arc', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.district')),
            ],
        ),
    ]
