# Generated by Django 3.0.7 on 2020-06-05 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('type', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.province'),
        ),
        migrations.AddField(
            model_name='motel',
            name='street',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.street'),
        ),
        migrations.AddField(
            model_name='motel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type'),
        ),
        migrations.AddField(
            model_name='motel',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.ward'),
        ),
    ]
